export const wigData = [
	{
		wig_id: '1',
		wig_name: 'Elegant Wavy Human Hair Wig',
		wig_type: 'Lace Front Wig',
		material: '100% Human Hair',
		texture: 'Wavy',
		color: 'Natural Black',
		length: '14 inches',
		density: '150%',
		cap_size: 'Average',
		price: '$199.99',
		description:
			'Achieve a sophisticated look with this elegant wavy human hair wig. The lace front creates a natural-looking hairline, and the wavy texture adds volume and movement. It is made from 100% human hair, allowing for versatile styling. The wig has a medium cap size and a comfortable fit with adjustable straps. Available in a stylish natural black color, perfect for daily wear or special occasions.',
		image_url: 'https://www.example.com/images/wig_1.jpg',
		availability: true,
	},
	{
		wig_id: '2',
		wig_name: 'Sleek Straight Synthetic Wig',
		wig_type: 'Standard Cap Wig',
		material: 'Synthetic Fiber',
		texture: 'Straight',
		color: 'Chocolate Brown',
		length: '20 inches',
		density: '130%',
		cap_size: 'Average',
		price: '$89.99',
		description:
			'Get a chic and sleek look with this straight synthetic wig. The standard cap design provides a secure fit, and the synthetic fiber allows for low-maintenance styling. The wig comes in a stunning chocolate brown shade and has a medium density for a natural appearance. Perfect for any occasion and easy to wear.',
		image_url: 'https://www.example.com/images/wig_20.jpg',
		availability: true,
	},

	{
		wig_id: '3',
		wig_name: 'Curly Bob Human Hair Wig',
		wig_type: 'Full Lace Wig',
		material: '100% Human Hair',
		texture: 'Curly',
		color: 'Golden Blonde',
		length: '12 inches',
		density: '120%',
		cap_size: 'Average',
		price: '$189.99',
		description:
			"Rock a trendy and playful look with this curly bob human hair wig. The full lace design offers a natural-looking hairline and allows for off-the-face styling. Made from 100% human hair, it provides a soft and bouncy texture that's easy to manage. The wig comes in a beautiful golden blonde shade, perfect for a chic and sassy style.",
		image_url: 'https://www.example.com/images/wig_21.jpg',
		availability: true,
	},
	{
		wig_id: '4',
		wig_name: 'Short Pixie Cut Synthetic Wig',
		wig_type: 'Standard Cap Wig',
		material: 'Synthetic Fiber',
		texture: 'Pixie Cut',
		color: 'Platinum Silver',
		length: '6 inches',
		density: '110%',
		cap_size: 'Average',
		price: '$69.99',
		description:
			'Embrace a bold and edgy look with this short pixie cut synthetic wig. The standard cap design ensures a secure fit, and the synthetic fiber offers a vibrant platinum silver color. With its short length and chic style, this wig is perfect for making a fashion statement and expressing your individuality.',
		image_url: 'https://www.example.com/images/wig_22.jpg',
		availability: true,
	},
	{
		wig_id: '5',
		wig_name: 'Elegant Wavy Human Hair Wig',
		wig_type: 'Lace Front Wig',
		material: '100% Human Hair',
		texture: 'Wavy',
		color: 'Natural Black',
		length: '14 inches',
		density: '150%',
		cap_size: 'Average',
		price: '$199.99',
		description:
			'Achieve a sophisticated look with this elegant wavy human hair wig. The lace front creates a natural-looking hairline, and the wavy texture adds volume and movement. It is made from 100% human hair, allowing for versatile styling. The wig has a medium cap size and a comfortable fit with adjustable straps. Available in a stylish natural black color, perfect for daily wear or special occasions.',
		image_url: 'https://www.example.com/images/wig_12345.jpg',
		availability: true,
	},
];



