export const ProductData = [
	{
		Product_id: '1',
		Productductductductduct_name: 'Elegant Wavy Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Wavy',
		color: 'Natural Black',
		length: '14 inches',
		density: '150%',
		cap_size: 'Average',
		price: '199.99',
		ratings: { comments: 52, stars: 4 },
		description:
			'Achieve a sophisticated look with this elegant wavy human hair Product. The lace front creates a natural-looking hairline, and the wavy texture adds volume and movement. It is made from 100% human hair, allowing for versatile styling. The Product has a medium cap size and a comfortable fit with adjustable straps. Available in a stylish natural black color, perfect for daily wear or special occasions.',
		image_url: 'https://www.example.com/images/Product_1.jpg',
		availability: true,
	},
	{
		Product_id: '2',
		Product_name: 'Sleek Straight Synthetic Product',
		Product_type: 'Standard Cap Product',
		material: 'Synthetic Fiber',
		texture: 'Straight',
		color: 'Chocolate Brown',
		length: '20 inches',
		density: '130%',
		cap_size: 'Average',
		price: '89.99',
		ratings: { comments: 32, stars: 3 },
		description:
			'Get a chic and sleek look with this straight synthetic Product. The standard cap design provides a secure fit, and the synthetic fiber allows for low-maintenance styling. The Product comes in a stunning chocolate brown shade and has a medium density for a natural appearance. Perfect for any occasion and easy to wear.',
		image_url: 'https://www.example.com/images/Product_20.jpg',
		availability: false,
	},

	{
		Product_id: '3',
		Product_name: 'Curly Bob Human Hair Product',
		Product_type: 'Full Lace Product',
		material: '100% Human Hair',
		texture: 'Curly',
		color: 'Golden Blonde',
		length: '12 inches',
		density: '120%',
		cap_size: 'Average',
		price: '189.99',
		ratings: { comments: 45, stars: 4 },
		description:
			"Rock a trendy and playful look with this curly bob human hair Product. The full lace design offers a natural-looking hairline and allows for off-the-face styling. Made from 100% human hair, it provides a soft and bouncy texture that's easy to manage. The Product comes in a beautiful golden blonde shade, perfect for a chic and sassy style.",
		image_url: 'https://www.example.com/images/Product_21.jpg',
		availability: true,
	},
	{
		Product_id: '4',
		Product_name: 'Short Pixie Cut Synthetic Product',
		Product_type: 'Standard Cap Product',
		material: 'Synthetic Fiber',
		texture: 'Pixie Cut',
		color: 'Platinum Silver',
		length: '6 inches',
		density: '110%',
		cap_size: 'Average',
		price: '69.99',
		ratings: { comments: 53, stars: 3 },
		description:
			'Embrace a bold and edgy look with this short pixie cut synthetic Product. The standard cap design ensures a secure fit, and the synthetic fiber offers a vibrant platinum silver color. With its short length and chic style, this Product is perfect for making a fashion statement and expressing your individuality.',
		image_url: 'https://www.example.com/images/Product_22.jpg',
		availability: true,
	},
	{
		Product_id: '5',
		Product_name: 'Elegant Wavy Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Wavy',
		color: 'Natural Black',
		length: '14 inches',
		density: '150%',
		cap_size: 'Average',
		price: '199.99',
		ratings: { comments: 20, stars: 2 },
		description:
			'Achieve a sophisticated look with this elegant wavy human hair Product. The lace front creates a natural-looking hairline, and the wavy texture adds volume and movement. It is made from 100% human hair, allowing for versatile styling. The Product has a medium cap size and a comfortable fit with adjustable straps. Available in a stylish natural black color, perfect for daily wear or special occasions.',
		image_url: 'https://www.example.com/images/Product_12345.jpg',
		availability: true,
	},

	{
		Product_id: '11',
		Product_name: 'Elegant Wavy Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Wavy',
		color: 'Natural Black',
		length: '14 inches',
		density: '150%',
		cap_size: 'Average',
		ratings: { comments: 42, stars: 4 },
		price: '199.99',
		description:
			'Achieve a sophisticated look with this elegant wavy human hair Product. The lace front creates a natural-looking hairline, and the wavy texture adds volume and movement. It is made from 100% human hair, allowing for versatile styling. The Product has a medium cap size and a comfortable fit with adjustable straps. Available in a stylish natural black color, perfect for daily wear or special occasions.',
		image_url: 'https://www.example.com/images/Product_1.jpg',
		availability: true,
	},

	{
		Product_id: '6',
		Product_name: 'Sleek Bob Synthetic Product',
		Product_type: 'Standard Cap Product',
		material: 'Synthetic Fiber',
		texture: 'Bob',
		color: 'Jet Black',
		length: '12 inches',
		density: '120%',
		cap_size: 'Average',
		ratings: { comments: 32, stars: 3 },
		price: '79.99',
		description:
			'Get a chic and sophisticated look with this sleek bob synthetic Product. The standard cap design provides a secure fit, and the synthetic fiber offers a glossy jet black color. The Product has a medium density and a comfortable average cap size. Perfect for everyday wear or special occasions, this Product is sure to turn heads.',
		image_url: 'https://www.example.com/images/Product_6.jpg',
		availability: true,
	},
	{
		Product_id: '7',
		Product_name: 'Long Curly Human Hair Product',
		Product_type: 'Full Lace Product',
		material: '100% Human Hair',
		texture: 'Curly',
		color: 'Medium Brown',
		length: '24 inches',
		density: '130%',
		cap_size: 'Average',
		ratings: { comments: 32, stars: 3 },
		price: '299.99',
		description:
			'Achieve glamorous and voluminous curls with this long curly human hair Product. The full lace design offers a natural-looking hairline, and the human hair material allows for versatile styling options. The Product comes in a beautiful medium brown color and has a comfortable average cap size. Perfect for special occasions or when you want to add drama to your look.',
		image_url: 'https://www.example.com/images/Product_7.jpg',
		availability: true,
	},
	{
		Product_id: '8',
		Product_name: 'Sleek Straight Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Straight',
		color: 'Dark Brown',
		length: '16 inches',
		density: '140%',
		cap_size: 'Average',
		ratings: { comments: 32, stars: 3 },
		price: '219.99',
		description:
			'Get a polished and sophisticated look with this sleek straight human hair Product. The lace front creates a seamless hairline, and the straight texture offers a sleek appearance. Made from 100% human hair, this Product allows for heat styling and can be easily customized. The Product has a medium cap size and is available in a versatile dark brown color.',
		image_url: 'https://www.example.com/images/Product_8.jpg',
		availability: true,
	},
	{
		Product_id: '9',
		Product_name: 'Short Layered Synthetic Product',
		Product_type: 'Standard Cap Product',
		material: 'Synthetic Fiber',
		texture: 'Layered',
		color: 'Auburn Red',
		length: '8 inches',
		density: '110%',
		cap_size: 'Average',
		price: '64.99',
		ratings: { comments: 23, stars: 3 },
		description:
			'Express your bold and trendy style with this short layered synthetic Product. The standard cap design ensures a comfortable fit, and the synthetic fiber offers a vibrant auburn red color. With its layered texture and chic style, this Product is perfect for making a fashion statement and adding a pop of color to your look.',
		image_url: 'https://www.example.com/images/Product_9.jpg',
		availability: true,
	},
	{
		Product_id: '10',
		Product_name: 'Beautiful Straight Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Straight',
		color: 'Honey Blonde',
		length: '18 inches',
		density: '130%',
		cap_size: 'Average',
		ratings: { comments: 12, stars: 4 },
		price: '249.99',
		description:
			'Achieve an elegant and glamorous look with this straight human hair Product. The lace front design creates a natural-looking hairline, and the straight texture offers a sleek appearance. Made from 100% human hair, this Product provides a soft and natural feel. The Product has a medium cap size and is available in a beautiful honey blonde shade.',
		image_url: 'https://www.example.com/images/Product_10.jpg',
		availability: true,
	},
	{
		Product_id: '10',
		Product_name: 'Elegant Straight Human Hair Product',
		Product_type: 'Lace Front Product',
		material: '100% Human Hair',
		texture: 'Straight',
		color: 'Honey Blonde',
		length: '18 inches',
		density: '130%',
		cap_size: 'Average',
		ratings: { comments: 12, stars: 4 },
		price: '249.99',
		description:
			'Achieve an elegant and glamorous look with this straight human hair Product. The lace front design creates a natural-looking hairline, and the straight texture offers a sleek appearance. Made from 100% human hair, this Product provides a soft and natural feel. The Product has a medium cap size and is available in a beautiful honey blonde shade.',
		image_url: 'https://www.example.com/images/Product_10.jpg',
		availability: true,
	},
];
